# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils

MY_PN=${PN/-/_}
MY_P="${MY_PN}-${PV}"

DESCRIPTION="An extension to PEAK-Rules to prioritize methods in order to to avoid AmbiguousMethods situations"
HOMEPAGE="UNKNOWN"
SRC_URI="http://pypi.python.org/packages/source/p/${MY_PN}/${MY_P}.tar.gz"
LICENSE="MIT"
KEYWORDS=""
SLOT="0"
IUSE=""

RDEPEND=">=dev-python/peak-rules-0.5_alpha1_pre2562"
DEPEND=""

S="${WORKDIR}/${MY_P}"
