# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils

MY_PN="SymbolType"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Simple 'symbol' type, useful for enumerations or sentinels"
HOMEPAGE="http://peak.telecommunity.com/DevCenter/SymbolType"
SRC_URI="http://pypi.python.org/packages/source/S/${MY_PN}/${MY_P}.zip"
LICENSE="ZPL"
KEYWORDS=""
SLOT="0"
IUSE=""

DEPEND="app-arch/unzip"

S="${WORKDIR}/${MY_P}"
