# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

inherit distutils

MY_PN="tgext.admin"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Admin Controller add-on for basic TG identity model."
HOMEPAGE="tgtools.googlecode.com"
SRC_URI="http://pypi.python.org/packages/source/t/${MY_PN}/${MY_P}.tar.gz"
LICENSE="MIT"
KEYWORDS=""
SLOT="0"
IUSE=""

RDEPEND=">=dev-python/tg-ext-crud-0.2.1"
DEPEND="dev-python/setuptools"

S="${WORKDIR}/${MY_P}"
