# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

# Warning: Invalid LICENSE.
inherit distutils

MY_PN="BytecodeAssembler"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Generate Python code objects by 'assembling' bytecode (Now includes a functional/AST-oriented API, too!)"
HOMEPAGE="http://pypi.python.org/pypi/BytecodeAssembler"
SRC_URI="http://pypi.python.org/packages/source/B/BytecodeAssembler/${MY_P}.zip"
LICENSE="ZPL"
KEYWORDS=""
SLOT="0"
IUSE=""
DEPEND="app-arch/unzip"

S="${WORKDIR}/${MY_P}"
