# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

inherit distutils

MY_PN="Catwalk"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A way to view your models using TurboGears"
HOMEPAGE="http://code.google.com/p/tgtools/wiki/Catwalk"
SRC_URI="http://pypi.python.org/packages/source/C/${MY_PN}/${MY_P}.tar.gz"
LICENSE="MIT"
KEYWORDS=""
SLOT="0"
IUSE=""

RDEPEND="dev-python/sprox
	dev-python/tg-ext-admin"

S="${WORKDIR}/${MY_P}"
