# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils

MY_PN="AddOns"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Dynamically extend other objects with AddOns (formerly ObjectRoles)"
HOMEPAGE="http://www.python.org/pypi/AddOns"
SRC_URI="http://pypi.python.org/packages/source/A/AddOns/${MY_P}.zip"
LICENSE="ZPL"
KEYWORDS=""
SLOT="0"
IUSE=""

RDEPEND=">=dev-python/decoratortools-1.5"
DEPEND="app-arch/unzip"

S="${WORKDIR}/${MY_P}"
