# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils

MY_PN="WebFlash"
MY_PV="${PV/_alpha/a}"
MY_P="${MY_PN}-${MY_PV}"

DESCRIPTION="Portable flash messages for WSGI apps"
HOMEPAGE="http://python-rum.org/wiki/WebFlash"
SRC_URI="http://pypi.python.org/packages/source/W/${MY_PN}/${MY_P}.tar.gz"
LICENSE="MIT"
KEYWORDS=""
SLOT="0"
IUSE=""

S="${WORKDIR}/${MY_P}"
