# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

inherit distutils

MY_PN="${PN/-/.}"
MY_PV="${PV/_beta/b}"
MY_P="${MY_PN}-${MY_PV}"

DESCRIPTION="Collection of repoze.who friendly form plugins"
HOMEPAGE="http://code.gustavonarea.net/repoze.who-friendlyform/"
SRC_URI="http://pypi.python.org/packages/source/r/${MY_PN}/${MY_P}.tar.gz"
LICENSE="Repoze"
KEYWORDS=""
SLOT="0"
IUSE=""

DEPEND=">=dev-python/repoze-who-1.0
	net-zope/zopeinterface"

S="${WORKDIR}/${MY_P}"
