# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

inherit distutils

DESCRIPTION="Python Gettext implementation."
HOMEPAGE="http://svn.plone.org/svn/collective/python-gettext/trunk"
SRC_URI="http://pypi.python.org/packages/source/p/${PN}/${P}.tar.gz"
LICENSE="GPL-2"
KEYWORDS=""
SLOT="0"
IUSE=""
