# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils

DESCRIPTION="repoze.who is an identification and authentication framework for WSGI."
HOMEPAGE="http://www.repoze.org"
SRC_URI="http://pypi.python.org/packages/source/r/repoze.who/${P}.tar.gz"
LICENSE="Repoze"
KEYWORDS=""
SLOT="0"
IUSE=""
