# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils

MY_PN="${PN/-/.}"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="repoze.who is an identification and authentication framework for WSGI."
HOMEPAGE="http://www.repoze.org"
SRC_URI="http://pypi.python.org/packages/source/r/${MY_PN}/${MY_P}.tar.gz"
LICENSE="Repoze"
KEYWORDS=""
SLOT="0"
IUSE=""

RDEPEND="net-zope/zopeinterface
	dev-python/paste"
DEPEND="dev-python/setuptools"

S="${WORKDIR}/${MY_P}"
