# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

inherit distutils

MY_PN="RunSnakeRun"
MY_PV="${PV/_beta/b}"
MY_P="${MY_PN}-${MY_PV}"

DESCRIPTION="GUI Viewer for Python profiling runs"
HOMEPAGE="http://www.vrplumber.com/programming/runsnakerun/"
SRC_URI="http://pypi.python.org/packages/source/R/RunSnakeRun/${MY_P}.zip"
LICENSE="BSD-2"
KEYWORDS=""
SLOT="0"
IUSE="doc"

S="${WORKDIR}/${MY_P}"

DEPEND="app-arch/unzip
	dev-python/setuptools"
RDEPEND="dev-python/wxpython
	dev-python/squaremap"

src_install() {
	distutils_src_install
	if use doc; then
		dodoc "${S}"/doc/*
	fi
}
