# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

inherit distutils

DESCRIPTION="Database schema migration for SQLAlchemy"
HOMEPAGE="http://code.google.com/p/sqlalchemy-migrate/"
SRC_URI="http://sqlalchemy-migrate.googlecode.com/files/${P}.tar.gz"
LICENSE="MIT"
KEYWORDS=""
SLOT="0"
IUSE="doc test"

RDEPEND=">=dev-python/sqlalchemy-0.5"
DEPEND="doc? ( >=dev-python/sphinx-0.5 )
	test? ( >=dev-python/nose-0.10 )"
