# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils

MY_PV="${PV/_alpha/a}"
MY_P="${PN}-${MY_PV}"

DESCRIPTION="Zope-like transaction manager via WSGI middleware"
HOMEPAGE="http://www.repoze.org"
SRC_URI="http://pypi.python.org/packages/source/r/${PN}/${MY_P}.tar.gz"
LICENSE="Repoze"
KEYWORDS=""
SLOT="0"
IUSE=""

RDEPENDS="dev-python/transaction"

S="${WORKDIR}/${MY_P}"
