# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils

MY_PV="${PV/_rc/rc}"
MY_P="${PN}-${MY_PV}"

DESCRIPTION="Test utilities for repoze.who-powered applications"
HOMEPAGE="http://code.gustavonarea.net/repoze.who-testutil/"
SRC_URI="http://pypi.python.org/packages/source/r/${PN}/${MY_P}.tar.gz"
LICENSE="Repoze"
KEYWORDS=""
SLOT="0"
IUSE=""

S="${WORKDIR}/${MY_P}"

RDEPEND=">=dev-python/repoze.who-1.0
		net-zope/zopeinterface
		>=dev-python/pastescript-1.7
		>=dev-python/pastedeploy-1.3.3"
