# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils

DESCRIPTION="An extension to PEAK-Rules to prioritize methods in order to to avoid AmbiguousMethods situations"
HOMEPAGE="UNKNOWN"
SRC_URI="http://pypi.python.org/packages/source/p/prioritized_methods/${P}.tar.gz"
LICENSE="MIT"
KEYWORDS=""
SLOT="0"
IUSE=""

