# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils

MY_PV="${PV/_alpha/a}"
MY_P="${PN}-${MY_PV}"

DESCRIPTION="Transaction management for Python"
HOMEPAGE="http://www.zope.org/Products/ZODB"
SRC_URI="http://pypi.python.org/packages/source/t/transaction/${MY_P}.tar.gz"
LICENSE="ZPL"
KEYWORDS=""
SLOT="0"
IUSE=""

RDEPEND="net-zope/zopeinterface"

S="${WORKDIR}/${MY_P}"
